import {expect,test} from "bun:test";
import {createComposition} from "../lib/dmgly/model";
import {electronConfig} from "../lib/dmgly/export/electron";
test("Electron exports exact icon centers and a resource-backed config",()=>{const d=createComposition();d.app.x=222;const result=electronConfig(d),config=JSON.parse(result.content);expect(config.dmg.contents[0]).toEqual({x:222,y:170,type:"file"});expect(config.dmg.contents[1].path).toBe("/Applications");expect(config.dmg.background.endsWith(result.assets[0])).toBe(true);expect(config.dmg.backgroundColor).toBeUndefined();expect(config.dmg.iconSize).toBe(128);});
import {tauriConfig} from "../lib/dmgly/export/tauri";
test("Tauri uses the nested DMG config with its supported fields",()=>{const d=createComposition(),r=tauriConfig(d),v=JSON.parse(r.content);expect(v.bundle.macOS.dmg.windowSize).toEqual(d.window);expect(v.bundle.macOS.dmg.appPosition).toEqual({x:180,y:170});expect(v.bundle.macOS.dmg.iconSize).toBeUndefined();expect(r.warnings.length).toBe(1);});
import {nativeConfig,shellQuote} from "../lib/dmgly/export/native";
import {spawnSync} from "node:child_process";
test("native script is valid Bash and handles paths via quoted arguments",()=>{const d=createComposition();d.app.name="App ' & $(touch unsafe)";const r=nativeConfig(d);const check=spawnSync("bash",["-n"],{input:r.content});expect(check.status).toBe(0);expect(r.content).not.toContain("touch unsafe");expect(r.content).toContain('--icon "$APP_NAME" 180 170');expect(r.content).toContain('[[ ! -e "$OUTPUT" ]]');expect(shellQuote("O'Reilly")).toBe("'O'\\''Reilly'");});
import {aiPrompt,fenced} from "../lib/dmgly/export/ai-prompt";
test("AI prompts use the selected target snapshot and safe data fences",()=>{const d=createComposition();d.app.name="My ``` App";d.text.visible=false;for(const get of [electronConfig,tauriConfig,nativeConfig]){const c=get(d),prompt=aiPrompt(d,c);expect(prompt).toContain(c.content);expect(prompt).toContain('"textBakedIn": false');expect(prompt).toContain(c.filename);expect(prompt).toContain("assets/dmg-background.png");}expect(fenced("```\ntext")).toStartWith("````\n");});
